## Matrices and Vectors

**Matrices** and **vectors** are fundamental concepts in linear algebra.

A **matrix** is a rectangular array of numbers arranged in rows and columns. For example, a 2x3 matrix has 2 rows and 3 columns:



```
A = [[a, b, c],
     [d, e, f]]
```

A **vector** is a special type of matrix that has only one row or one column. For example, a column vector with 3 elements looks like this:

```
v = [[x],
     [y],
     [z]]
```



The **product** of a matrix `A` and a vector `v` is another vector `Av` that's obtained by multiplying each row of `A` by `v` and summing the results. In order for this product to be defined, the number of columns in `A` must be equal to the number of rows in `v`. In general If you have a **row vector** and a **matrix**, the vector should be on the **left** of the product i.e. `v.A`, and if you have a column vector and a matrix, the vector should be on the right of the product i.e. `A.v`.

```
M = [[a, b],
     [c, d]]

v = [[x],
     [y]]
```
the product of Mv would be
```
Mv = [[ax + by],
      [cx + dy]]
```

The **inverse** of a square matrix `A` (a matrix with the same number of rows and columns) is a matrix `A^-1` such that the product `AA^-1` is the identity matrix. The identity matrix is a special square matrix that has 1s on the diagonal and 0s elsewhere. Not all matrices have an inverse; if an inverse exists, it can be computed using various algorithms.

Here's an example in Python using the `numpy` library. The code first computes the product of `A` and `v`, then computes the inverse of `A`, and finally verifies that `AA^-1` is the identity matrix.

In [14]:
import numpy as np

# Define a 3x3 matrix A and a row vector v
A = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 1]])
v = np.array([2, 1, 3])

# Compute the product Av
Av = np.dot(A, v)
print(Av)

# Compute the inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

# Verify that AA^-1 is the identity matrix
I = np.dot(A, A_inv)
print(I)

is_identity = np.allclose(I, np.eye(I.shape[0]))
print(is_identity)


[13 31  7]
[[-1.16666667  0.66666667 -0.5       ]
 [ 0.33333333 -0.33333333  1.        ]
 [ 0.5        -0.         -0.5       ]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.44089210e-16 1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00 1.00000000e+00]]
True
